// export const GET_SHOPPINGCAR_REQUEST = 'GET_SHOPPINGCAR_REQUEST';

export const ADD_PRODUCT_REQUEST = 'ADD_PRODUCT_REQUEST';

export const REMOVE_PRODUCT_REQUEST = 'REMOVE_PRODUCT_REQUEST';

export const ADD_QUANTITY_REQUEST = 'ADD_QUANTITY_REQUEST';

export const SUBTRACT_QUANTITY_REQUEST = 'SUBTRACT_QUANTITY_REQUEST';

export const CLEAR_SHOPPINGCAR = 'CLEAR_SHOPPINGCAR';
